= JDBSEE - CLI
Davide Cavestro <https://github.com/davidecavestro[@davidecavestro]>
// Settings:
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
:toc: macro
:toclevels: 1
endif::[]
ifdef::env-github[]
:branch: master
:status:
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
// URIs:
:uri-repo: https://github.com/davidecavestro/jdbsee
:uri-issues: {uri-repo}/issues
:uri-search-issues: {uri-repo}/search?type=Issues
:uri-ci-travis: https://travis-ci.org/davidecavestro/jdbsee
:uri-coverage-coveralls: https://coveralls.io/github/davidecavestro/jdbsee?branch=master
ifdef::status[]
image:https://img.shields.io/github/license/davidecavestro/jdbsee.svg[Apache License 2.0, link=#copyright-and-license]
image:https://img.shields.io/travis/davidecavestro/jdbsee/master.svg[Build Status (Travis CI), link={uri-ci-travis}]
image:https://img.shields.io/coveralls/github/davidecavestro/jdbsee.svg[Coverage Status (Coveralls), link={uri-coverage-coveralls}]
endif::[]

POC for a jdbc CLI tool

toc::[]


This is a POC for a jdbc CLI tool.

== Project status

Beware the project is still on an early stage.


== Features

The set of available commands will expand. As of now only a subset of 
the `run` command features are implemented.


== Usage


Invoke the distributable binary passing appropriate commands and params


=== `run` command 

```
Usage: run [-f=<sqlFile>] [-p=<password>] [-u=<username>] [-x=<execute>]... URL
           QUERY...
      URL                     The JDBC url.
      QUERY...                The SQL to run.
  -f, --file=<sqlFile>        File containing the query to run.
  -p, --password=<password>   The password
  -u, --user=<username>       The username
  -x, --execute=<execute>     Additional SQL commands to be executed before the
                                specified QUERY
```


== How to build

Build and launch some queries on an in-memory h2 db

```
./gradlew installDist && \
./build/install/jdbsee/bin/jdbsee run \
-x "create table contacts (id int primary key, name varchar(100));" \
-x "insert into contacts (id, name) values (1, 'Alice');" \
-x "insert into contacts (id, name) values (2, 'Bob');" \
-x "insert into contacts (id, name) values (3, 'John');" \
-x "insert into contacts (id, name) values (4, 'Daisy');" \
"jdbc:h2:mem:test" \
"SELECT * FROM contacts;"
```

you should get

```
┌───────────────────────────────────────┬──────────────────────────────────────┐
│ID                                     │NAME                                  │
├───────────────────────────────────────┴──────────────────────────────────────┤
│1                                      │Alice                                 │
├───────────────────────────────────────┼──────────────────────────────────────┤
│2                                      │Bob                                   │
├───────────────────────────────────────┼──────────────────────────────────────┤
│3                                      │John                                  │
├───────────────────────────────────────┼──────────────────────────────────────┤
│4                                      │Daisy                                 │
└───────────────────────────────────────┴──────────────────────────────────────┘

```

== TO-DO

* Support exporting results (json, csv)
* Support using drivers from local jars
* Support downloading drivers with grapes
* Support named drivers (persisting additional driver config)
* Support named datasoruces (persisting db access config)
